/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class calculate */

#ifndef _Included_calculate
#define _Included_calculate
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     calculate
 * Method:    multiply
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_calculate_multiply
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
